linters:
  enable-all: true

  disable:
    - funlen
    - lll
    - gocognit
    - gocyclo
    - exhaustivestruct
    - varnamelen
    - gomnd
    - godox
    - nestif
    - wsl
    - nolintlint
    - exhaustruct

run:
  timeout: 10m
