apiVersion: security.nirmata.io/v1alpha1
kind: AWSAdapterConfig
metadata:
  labels:
    app.kubernetes.io/name: awsadapterconfig
    app.kubernetes.io/instance: awsacfg-sample
    app.kubernetes.io/part-of: kyverno-aws-adapter
    app.kubernetes.io/created-by: kyverno-aws-adapter
  name: test-config
  namespace: default
spec:
  name: test
  region: us-west-1
