apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kyverno-aws-adapter.fullname" . }}
  labels:
    {{- include "kyverno-aws-adapter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kyverno-aws-adapter.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "kyverno-aws-adapter.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - /manager
        image: {{ include "kyverno-aws-adapter.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: manager
        {{- if .Values.pollInterval }}
        args:
        - --sync-period={{ .Values.pollInterval }}
        {{- end }}
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: {{ include "kyverno-aws-adapter.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
