{{- if .Values.rbac.create }}
# permissions for end users to edit awsadapterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kyverno-aws-adapter.fullname" . }}
  labels:
    {{- include "kyverno-aws-adapter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.nirmata.io
  resources:
  - awsadapterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - awsadapterconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - awsadapterconfigs/finalizers
  verbs:
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kyverno-aws-adapter.serviceAccountName" . }}
  labels:
    {{- include "kyverno-aws-adapter.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "Role ARN is required" .Values.roleArn }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kyverno-aws-adapter.fullname" . }}
  labels:
    {{- include "kyverno-aws-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kyverno-aws-adapter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kyverno-aws-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
