# permissions for end users to edit awsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nirmata-aws-adapter
    app.kubernetes.io/part-of: nirmata-aws-adapter
  name: awsconfig-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - patch
- apiGroups:
  - security.nirmata.io
  resources:
  - awsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - awsconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - awsconfigs/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: awsconfig-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nirmata-aws-adapter
    app.kubernetes.io/part-of: nirmata-aws-adapter
  name: awsconfig-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awsconfig-manager-role
subjects:
- kind: ServiceAccount
  name: nirmata-aws-adapter-sa
  namespace: {{ .Values.namespace.name }}
