kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ include "nirmata-aws-adapter.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "nirmata-aws-adapter.fullname" . }}
data:
  .dockerconfigjson: {{ include "nirmata-aws-adapter.dockerconfigjson" . }}
