name: Build

on:
  push:
    branches:
      - 'main'
      - 'release*'
  pull_request:
    branches:
      - 'main'
      - 'release*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Update codegen
        run: make manifests generate fmt
      - name: Go mod tidy
        run: go mod tidy
      - name: Verify go mod
        run: |
          set -e
          git --no-pager diff go.mod
          git diff --quiet --exit-code go.mod
          git --no-pager diff go.sum
          git diff --quiet --exit-code go.sum
      - name: Verify codegen
        run: |
          set -e
          git --no-pager diff config
          git diff --quiet --exit-code config
          git --no-pager diff api
          git diff --quiet --exit-code api
      - name: Make build
        run: make build
      - name: Run go vet
        run: make vet
